#!/usr/bin/env ruby

require "docopt"

begin
  cli = Docopt.docopt(<<~DOCOPT)
    Usage:
      wal watch --watcher <watcher-class>
        (--slot <replication-slot> | --tmp-slot)
        [--publication=<publication>...]
        [--replicator <replicator-class>]
      wal start <config-file>

    Options:
      -h --help                          Show this screen.
      --watcher=<watcher-class>          The watcher class to be used to listen for WAL changes.
      --slot=<replication-slot>          The replication slot that will be used.
      --tmp-slot                         Use a temporary replication slot.
      [--publication=<publication>...]   Force using the informed Postgres publications.
      [--replicator=<replicatior_class>] Change the replication driver class
  DOCOPT
rescue Docopt::Exit => err
  puts err.message
  exit
end

require "./config/environment"

db_config = ActiveRecord::Base.configurations.configs_for(name: "primary").configuration_hash

def watch(db_config, cli)
  watcher = cli["--watcher"].constantize.new
  use_temporary_slot = cli["--tmp-slot"] || false
  replication_slot = cli["--slot"]
  replication_slot = replication_slot.presence || "wal_watcher_#{SecureRandom.alphanumeric(4)}" if use_temporary_slot
  publications = cli["--publication"] || []
  replicator_class = cli["--replicator"].presence&.constantize || Wal::Replicator

  puts "Watcher started for #{replication_slot} slot (#{publications.join(", ")})"
  replicator_class
    .new(replication_slot:, use_temporary_slot:, db_config:)
    .replicate_forever(Wal::LoggingWatcher.new(replication_slot, watcher), publications:)
  puts "Watcher finished for #{replication_slot}"
end

if cli["watch"]
  watch(db_config, cli)
elsif cli["start"]
  runner = Wal::Runner.new(config_file: cli["<config-file>"], db_config:)
  runner.start
end
